spring.application.name=dai-api

spring.autoconfigure.exclude=\
org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,\
org.springframework.boot.orm.jpa.autoconfigure.HibernateJpaAutoConfiguration